### ISSUE TITLE
VDS 3102 on linux

### ISSUE THREAD

**Issue by adrianre12** [florentbr/OWON-VDS1022#102]
Hi,
I am looking at trying to get the SW for the VDS 3102 running in Linux. Looking at your code it seems that the install is changing the USB library, then copying in the Owon jars etc.
I know you have made improvements to the Owon code, but If I want to get the vanilla VDS3102 code running do I need to make any changes to the Owon code?

**Comment by florentbr** [comment]
Most likely. It could be just a few lines of code depending on the driver.
I only have a VDS1022, so you are on your own.
