### ISSUE TITLE
OWON RDS support?

### ISSUE THREAD

**Issue by machjiri22** [florentbr/OWON-VDS1022#13]
Hi,

is there any chance of adding [OWON RDS osciloscope](https://www.owon.com.hk/products_owon_pen-type_pc_oscilloscope) support? Original software from OWON looks exactly the same as for VDS, only diference is missing second channel.

I tried your application  but it keeps telling me no USB device found despite RDS should use the same linux driver "ID 5345:1234 Owon PDS6062T Oscilloscope". But it obviously registering my Owon RDS somehow, because when I run from command line and connect my device it start to send me "machineCode: 2" periodically till I disconnect it

**Comment by florentbr** [comment]
The software for the RDS is different. Even though it looks alike, a significant portion of the code is different. Have a look at issue #11 if you wish to port the RDS software to a non Windows OS.
