### ISSUE TITLE
Adding message reader module (i2c, uart...)

### ISSUE THREAD

**Issue by Montaire** [florentbr/OWON-VDS1022#15]
Do you think it is possible to add a message reader module to the software?
If you think it is feasible, and you accept contributions, can you give me directions where to start? I am a computer engineer by trade, and I would be happy to contribute to your project!

**Comment by florentbr** [comment]
It's not worth the effort compared to the price of a logic analyser. The 5k buffer holds at most 3 or 4 bytes of decoded data. It's possible to continuously read the buffer while the device fills it in a loop. Unfortunately the cursor (writing offset) is not available. You could probably find the position based on the timing and by comparing the current/previous frame but it may be unreliable depending on the data. Also USB 2 is quite slow, the stitching will quickly fail with high sampling rates.
