### ISSUE TITLE
Unable to launch under MacOS Big Sur

### ISSUE THREAD

**Issue by igor1661** [florentbr/OWON-VDS1022#16]
Hi --
Unable to start release 1.0.33-cf11 under MacOS Big Sur version 11.1.
The previous versions work fine.
Igor

**Comment by florentbr** [comment]
This issue is due to a regression introduced by release 1.0.33-cf11. To make it work, remove `-XstartOnFirstThread\\` line 66 in `install-mac.sh`.

**Comment by igor1661** [comment]
I've removed the line 66 from the install-mac.sh. 
Now it works as expected.
Thank you!

**Comment by florentbr** [comment]
keeping this issue open until fixed

**Comment by florentbr** [comment]
fixed in release 1.0.33-cf12
