### ISSUE TITLE
single trigger memory extention

### ISSUE THREAD

**Issue by John-By** [florentbr/OWON-VDS1022#27]
The displayed/saved timespan is always only as long, as the window is width.

This is especially an issue in single trigger mode, where it would be handy to see a longer timespan before and especially after a trigger event.

Is it possible to extend it by using the computer’s memory?

**Comment by florentbr** [comment]
The device holds a 5k buffer per channel, so 5000 samples per triggered input.
I don't think it's possible to extend the numbers of samples since the triggering and positioning is handled by the device.
