### ISSUE TITLE
Error Mark Cursor Menu: Aplitude no color change

### ISSUE THREAD

**Issue by km-linux** [florentbr/OWON-VDS1022#28]
Hi Florent,
While testing for the new documentation, I noticed an error in the 
**Mark Cursor Menu:**
**Channel**
**Amplitude** color always stays green, when selecting an other color.

![MarkCursor-Color](https://user-images.githubusercontent.com/72450024/110019268-8ea0d180-7d28-11eb-9e9b-54a2a62f38b3.png)

**Comment by florentbr** [comment]
As of release cf12, the amplitude cursor takes the colour and measures of the selected/highlighted channel. Switching between channels with TAB or mouse will change the colour and values accordingly. The colour button in Cursor/Channel now only affects the time cursor. I haven't touched yet the cursors of the FFT graph.

**Comment by km-linux** [comment]
When I have changed the documentation, I will close the issue.

**Comment by km-linux** [comment]
Documentation changed.

**Comment by km-linux** [comment]
> Switching between channels with TAB or **mouse** will change the colour and values accordingly.

**How to switch with the mouse?**
The **pulldown menu** for channel selection **behind Channel --> Amplitude does not exist** in this release.

**Comment by florentbr** [comment]
> How to switch with the mouse?
> The pulldown menu for channel selection behind Channel --> Amplitude does not exist in this release.

To select a channel, click on the channel area on the main window (element 18/19 from the doc). The selected channel is also used by some shortcuts like invert, coupling, offset, trigger, probe ratio.

**Comment by km-linux** [comment]
Documentation changed.

**Comment by km-linux** [comment]
Fixed
