### ISSUE TITLE
Russian language support

### ISSUE THREAD

**Issue by LeonIndman** [florentbr/OWON-VDS1022#29]
Hello florentbr! Thank you very much for another successful software update!
I would like to make corrections to the Russian language support files. I am attaching them to my post.

**Comment by LeonIndman** [comment]
![NewRu](https://user-images.githubusercontent.com/16102809/110624131-db642c80-81ae-11eb-829f-bcf460923418.jpg)
[shortcuts.zip](https://github.com/florentbr/OWON-VDS1022/files/6115512/shortcuts.zip)
[MsgLib_ru.zip](https://github.com/florentbr/OWON-VDS1022/files/6115547/MsgLib_ru.zip)

**Comment by LeonIndman** [comment]
I would also like to ask you to correct a small blot in this menu, which is shown in the 
![error2](https://user-images.githubusercontent.com/16102809/110625943-27b06c00-81b1-11eb-9129-7c57c86dedb1.jpg)
screenshot.

**Comment by km-linux** [comment]
Hello  LeonIndman,
I'm writing a completely new book for the software.
look at issue **German documentation for Owon VDS1022(I)/VDS2052(I)**

**If you are interested for translation in Russian language let me know.**

I write it with **OpenOffice, text and images separated.** 
The book is nearly ready.
It will be corrected by florentbr.
I write the book in two languages English and German.
I will place the documents in a shared folder on Google drive.

**Comment by LeonIndman** [comment]
Hello km-linux!
Thanks for the offer! When the book is ready, I will be able to see how extensive the work of translation into Russian will be.

**Comment by florentbr** [comment]
Fixed in release [1.1.1-cf13](https://github.com/florentbr/OWON-VDS1022/tags)
