### ISSUE TITLE
About massage / Update Link

### ISSUE THREAD

**Issue by km-linux** [florentbr/OWON-VDS1022#30]
When I click the button **About**, I get this message:

![about](https://user-images.githubusercontent.com/72450024/110820710-a380e600-828f-11eb-9895-9c8feb4f3a56.png)

The label shows **http://www.owon.com.hk/**, but the link from the **Update** button jumps to **https://github.com/florentbr/OWON-VDS1022/**

**What do you think about to change the OWON label?**

**Comment by florentbr** [comment]
Fixed in [release 1.1.1-cf13](https://github.com/florentbr/OWON-VDS1022/tags)
