### ISSUE TITLE
SCPI Console auto start

### ISSUE THREAD

**Issue by vistana-con** [florentbr/OWON-VDS1022#31]
I want to use the "Client.exe" from "http://files.owon.com.cn//software/Application/VDS_Series_SCPI_example_folder.zip" to communicate with VCD1022 oscilloscope.
I observed that it works only if SCPI Console is opened and Port 5188 was successfully settled.
Is it any solution to start this application, from command line, and have silently opened the SCPI Console ?

**Comment by florentbr** [comment]
The app needs to be launched for the SCPI server to work.
Note that there's now an API to directly communicate with the device with Python.
