### ISSUE TITLE
Raspberry Pi - VDS2062 can't connect

### ISSUE THREAD

**Issue by freezeghost** [florentbr/OWON-VDS1022#36]
Hello,

thank you for your great job. I try to connect mine VDS2062. But I am still offline. I try to your soft also on Windows and without success to connect this type of oscilloscope. It is supported?
I can see this scope in device list (lsusb) named as "Owon PDS6062T Oscilloscope"

thank you for your help

**Comment by florentbr** [comment]
The software for the VDS2062 is different compared to the VDS1022.
