### ISSUE TITLE
Cursor metering amplitude

### ISSUE THREAD

**Issue by Dezmond2** [florentbr/OWON-VDS1022#37]
Problem reading digits from cursor amplitude
![image](https://user-images.githubusercontent.com/12988501/130502141-cc335801-0129-4c57-b47e-258a4ebbd99b.png)

**Comment by florentbr** [comment]
I'll had a dark rectangle under the labels in the next release.

**Comment by Dezmond2** [comment]
> I'll had a dark rectangle under the labels in the next release.

Original owon software have good solution for this)

**Comment by florentbr** [comment]
Fixed in [release 1.1.1-cf13](https://github.com/florentbr/OWON-VDS1022/tags)
