### ISSUE TITLE
Math channel (Enhancenment)

### ISSUE THREAD

**Issue by rcalders** [florentbr/OWON-VDS1022#42]
Hello Florent,

I'd like to make an enhancement proposal. for future releases. 

It would be very convenient to have cursors on math channel.( I really don't understand why the official software doesn't provide them!)

It would also be very nice to have automatic measurements available for the math channel (rms, avg, etc.).

Thank you very much & great work!

**Comment by florentbr** [comment]
I added the Math measures in release [1.1.1-cf13](https://github.com/florentbr/OWON-VDS1022/tags)
