### ISSUE TITLE
Russian Language Update

### ISSUE THREAD

**Issue by LeonIndman** [florentbr/OWON-VDS1022#45]
Hi, florentbr! Thank you very much for another software update! That's great work on your part.
I would like to complete the translation of the interface menu into Russian, as I have found and corrected some errors and inaccuracies.
I am attaching the corrected files to the post.
https://drive.google.com/file/d/1nUzBwf5KO3A7N5XiYklhE891CohFY6PU/view?usp=sharing

**Comment by florentbr** [comment]
I'll include these changes in the next release.

**Comment by florentbr** [comment]
added to release [1.1.1-cf14](https://github.com/florentbr/OWON-VDS1022/tags)
