### ISSUE TITLE
硬件频率计问题

### ISSUE THREAD

**Issue by jwtn** [florentbr/OWON-VDS1022#49]
VDS1022原来硬件频率计是6位的，现在显示变成了4位，能不能改回来呢

**Comment by jwtn** [comment]
![fre1](https://user-images.githubusercontent.com/38699326/158069329-e0f075b4-1042-4ca0-9425-7fe2fba86e46.png)

**Comment by florentbr** [comment]
fixed in release 1.1.1-cf15

**Comment by jwtn** [comment]
感谢你的无私贡献，问题解决了
Thank you for your selfless contribution, the problem is solved
