### ISSUE TITLE
Full screen XY mode?

### ISSUE THREAD

**Issue by Trace-2** [florentbr/OWON-VDS1022#53]
Is it possible to get XY mode in full screen like the FFT screen? Maybe I just haven't found how to do it?

When FFT is enabled it can be toggled to full screen with the "to three view/to one view" button above "trigger" (bottom right).

I use XY mode a lot sometimes when troubleshooting & it would help me if I could full screen view the XY screen to see it better from where I sit, is that possible?

**Comment by Trace-2** [comment]
That would be fanatastic ... :)

**Comment by florentbr** [comment]
added to release 1.1.3-cf17
